name: Release
on:
  push:
    tags:
      - 'v**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get gradle properties
        uses: madhead/read-java-properties@latest
        id: gradle-properties
        with:
          file: gradle.properties
          all: true
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Generate Javadocs
        run: ./gradlew javadoc
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        id: ghRelease
        with:
          body_path: CHANGELOG.md
          name: ${{ steps.tagName.outputs.tag }}
          files: |
            Common/build/libs/*.jar
            Fabric/build/libs/*.jar
            Forge/build/libs/*.jar
      - name: Janky mc-publish fix - copy mod files to root
        run: |
          mkdir -p src/main/resource/META-INF
          cp Fabric/src/main/resources/fabric.mod.json ./src/main/resources
          cp Forge/src/main/resources/META-INF/mods.toml ./src/main/resources/META-INF
      - name: Fabric mod release
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: IlyLeWOY
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 702601
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          changelog-file: CHANGELOG.md
          files-primary: Fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
          files-secondary: Fabric/build/libs/*-@(dev|sources|javadoc).jar
          loaders: |
            fabric
            quilt
          name: Fabric ${{ steps.gradle-properties.outputs.minecraft_version }}-${{ steps.tagName.outputs.tag }}
          version: ${{ steps.tagName.outputs.tag }}
          game-versions: ${{ steps.gradle-properties.outputs.minecraft_version }}
      - name: Forge mod release
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: IlyLeWOY
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 702601
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          changelog-file: CHANGELOG.md
          files-primary: Forge/build/libs/!(*-@(dev|sources|javadoc)).jar
          files-secondary: Forge/build/libs/*-@(dev|sources|javadoc).jar
          loaders: |
            forge
          name: Forge ${{ steps.gradle-properties.outputs.minecraft_version }}-${{ steps.tagName.outputs.tag }}
          version: ${{ steps.tagName.outputs.tag }}
          game-versions: ${{ steps.gradle-properties.outputs.minecraft_version }}
      - name: Deploy Javadocs
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: Common/build/docs/javadoc/
          TARGET_FOLDER: javadoc
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Stop Gradle daemon
        run: ./gradlew --stop