name: Release
on:
  push:
    tags:
      - 'v**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Generate Javadocs
        run: ./gradlew javadoc
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        id: ghRelease
        with:
          body_path: CHANGELOG.md
          name: ${{ steps.tagName.outputs.tag }}
          files: |
            Common/build/libs/*.jar
            Fabric/build/libs/*.jar
            Forge/build/libs/*.jar
      - name: Deploy Javadocs
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: build/docs/javadoc/
          TARGET_FOLDER: javadoc
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Stop Gradle daemon
        run: ./gradlew --stop